lr: 0.01
epoches: 1000
batch_size: 800
data_file: "dataset_train.csv"
mode: "train"
model_file: ""

features:
    Arithmancy: False
    Astronomy: False
    Herbology: False
    Defense Against the Dark Arts: True
    Divination: True
    Muggle Studies: False
    Ancient Runes: True
    History of Magic: False
    Transfiguration: False
    Potions: False
    Care of Magical Creatures: False
    Charms: True
    Flying: True